local M = {}

M.rules = {
  ["bat"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%@REM.*]=],
    enabled = false,
  },
  ["clojure"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%%;%;.*]=],
    enabled = false,
  },
  ["coffeescript"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%#.*]=],
    enabled = false,
  },
  ["cpp"] = {
    increase = [=[\v^.*(\{[^}]*|\([^)]*|\[[^\]]*)$]=],
    decrease = [=[\v^\s*[\}\]\)].*$]=],
    comment = [=[%/%/.*]=],
    enabled = false,
  },
  ["cs"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%/%/.*]=],
    enabled = false,
  },
  ["css"] = {
    increase = [=[\v(^.*\{[^}]*$)]=],
    decrease = [=[\v^\s*\}]=],
    comment = nil,
    enabled = false,
  },
  ["dart"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%/%/.*]=],
    enabled = false,
  },
  ["diff"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%#.*]=],
    enabled = false,
  },
  ["docker"] = {
    increase = [=[\v^\s*.*(:|-) ?(&amp;\w+)?(\{[^}"']*|\([^)"']*)?$]=],
    decrease = [=[\v^\s+\}$]=],
    comment = [=[%#.*]=],
    enabled = false,
  },
  ["dotenv"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%#.*]=],
    enabled = false,
  },
  ["fsharp"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%/%/.*]=],
    enabled = false,
  },
  ["go"] = {
    increase = [=[\v^.*(<case>.*:|<default>:|(>(func|if|else|switch|select|for|struct)>.*)?{[^}"'`]*|\([^)"'`]*)$]=],
    decrease = [=[\v^\s*(<case>.*:|<default>:|}[)}]*[)]?|\)[]?)$]=],
    comment = [=[%/%/.*]=],
    enabled = false,
  },
  ["groovy"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%/%/.*]=],
    enabled = false,
  },
  ["handlebars"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = nil,
    enabled = false,
  },
  ["hlsl"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%/%/.*]=],
    enabled = false,
  },
  ["html"] = {
    increase = [=[\v<(?!\?|(?:area|base|br|col|frame|hr|html|img|input|keygen|link|menuitem|meta|param|source|track|wbr)>|[^>]*\/>)([-_\.A-Za-z0-9]+)(?=\s|>)>[^>]*>(?!.*<\/\1>)|<!--(?!.*-->)|\{[^}"']*$]=],
    decrease = [=[\v^\s*(<\/(?!html)[-_\.A-Za-z0-9]+>[^>]*>|-->|\})]=],
    comment = nil,
    enabled = false,
  },
  ["ini"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%#.*]=],
    enabled = false,
  },
  ["java"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%/%/.*]=],
    enabled = false,
  },
  ["javascript"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = nil,
    enabled = false,
  },
  ["json"] = {
    increase = [=[\v({+(?=((\\.|[^"\\])*"(\\.|[^"\\])*")*[^"}]*)$)|(\[+(?=((\\.|[^"\\])*"(\\.|[^"\\])*")*[^"\]]*)$)]=],
    decrease = [=[\v^\s*[}\]],?\s*$]=],
    comment = [=[%/%/.*]=],
    enabled = false,
  },
  ["julia"] = {
    increase = [=[\v^(\s*|.*=\s*|.*@\w*\s*)[\w\s]*(?:["'`][^"'`]*["'`])*[\w\s]*>(if|while|for|function|macro|(mutable\s+)?struct|abstract\s+type|primitive\s+type|let|quote|try|begin|.*\)\s*do|else|elseif|catch|finally)>(?!(?:.*<end>[^\]]*)|(?:[^\[]*\].*)$).*$]=],
    decrease = [=[\v^\s*(end|else|elseif|catch|finally)>.*$]=],
    comment = [=[%#.*]=],
    enabled = false,
  },
  ["latex"] = {
    increase = [=[\v\<egin{(?!document)([^}]*)}(?!.*\\end{\1})]=],
    decrease = [=[\v^\s*\\end{(?!document)]=],
    comment = nil,
    enabled = false,
  },
  ["less"] = {
    increase = [=[\v(^.*\{[^}]*$)]=],
    decrease = [=[\v^\s*\}]=],
    comment = [=[%/%/.*]=],
    enabled = false,
  },
  ["lua"] = {
    increase = [=[\v^((?!(\-\-)).)*((>(else|function|then|do|repeat)>((?!>(end|until)>).)*)|(\{\s*))$]=],
    decrease = [=[\v^\s*((>(elseif|else|end|until)>)|(\})|(\)))]=],
    comment = [=[%-%-.*]=],
    enabled = false,
  },
  ["make"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = nil,
    enabled = false,
  },
  ["markdown"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = nil,
    enabled = false,
  },
  ["objective-c"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%/%/.*]=],
    enabled = false,
  },
  ["perl"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%#.*]=],
    enabled = false,
  },
  ["prompt-basics"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = nil,
    enabled = false,
  },
  ["ps1"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%#.*]=],
    enabled = false,
  },
  ["python"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%#.*]=],
    enabled = false,
  },
  ["r"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%#.*]=],
    enabled = false,
  },
  ["razor"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = nil,
    enabled = false,
  },
  ["restructuredtext"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%.%..*]=],
    enabled = false,
  },
  ["ruby"] = {
    increase = [=[\v^\s*((begin|class|((private|protected)\s+)?def|else|elsif|ensure|for|if|module|rescue|unless|until|when|while|case)>|([^#]*\sdo>)|([^#]*\=\s*(case|if|unless)>))([^#{;]*)$]=],
    decrease = [=[\v^\s*([\}\]\)]|(end|else|elsif|ensure|rescue|when)>)]=],
    comment = [=[#.*]=],
    enabled = true,
    align_dot_chains = true,
  },
  ["rust"] = {
    increase = [=[\v^.*\{[^}"']*$|^.*\([^)"']*$]=],
    decrease = [=[\v^\s*(\s*/\*.*\*/\s*)*[})]]=],
    comment = [=[//.*]=],
    enabled = true,
    align_dot_chains = false,
  },
  ["scss"] = {
    increase = [=[\v(^.*\{[^}]*$)]=],
    decrease = [=[\v^\s*\}]=],
    comment = [=[%/%/.*]=],
    enabled = false,
  },
  ["sh"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%#.*]=],
    enabled = false,
  },
  ["shaderlab"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%/%/.*]=],
    enabled = false,
  },
  ["sql"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%-%-.*]=],
    enabled = false,
  },
  ["swift"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[%/%/.*]=],
    enabled = false,
  },
  ["typescript"] = {
    increase = [=[\v^.*(\{[^}]*|\([^)]*|\[[^\]]*)$]=],
    decrease = [=[\v^\s*[\}\]\)].*$]=],
    comment = [=[%/%/.*]=],
    enabled = false,
  },
  ["vb"] = {
    increase = [=[\v^\s*((If|ElseIf)>.*<Then\s*(('|REM).*)?|(Else|While|For|Do|Select\s+Case|Case|Sub|Function|Class|Module|Enum|Structure|Interface|Namespace|With|Try|Catch|Finally|SyncLock|Using|Property|Get|Set|AddHandler|RaiseEvent|RemoveHandler|Event|Operator)>(?!.*<End\s+(If|Sub|Function|Class|Module|Enum|Structure|Interface|Namespace|With|Select|Try|While|For|Property|Get|Set|SyncLock|Using|AddHandler|RaiseEvent|RemoveHandler|Event|Operator)>).*(('|REM).*)?)$]=],
    decrease = [=[\v^\s*((End\s+(If|Sub|Function|Class|Module|Enum|Structure|Interface|Namespace|With|Select|Try|While|For|Property|Get|Set|SyncLock|Using|AddHandler|RaiseEvent|RemoveHandler|Event|Operator))|Else|ElseIf|Case|Catch|Finally|Loop|Next|Wend|Until)>]=],
    comment = [=[%'.*]=],
    enabled = false,
  },
  ["xml"] = {
    increase = [=[]=],
    decrease = [=[]=],
    comment = [=[.*]=],
    enabled = false,
  },
  ["yaml"] = {
    increase = [=[\v^\s*.*(:|-) ?(&amp;\w+)?(\{[^}"']*|\([^)"']*)?$]=],
    decrease = [=[\v^\s+\}$]=],
    comment = [=[%#.*]=],
    enabled = false,
  },
}

return M
